CREATE TABLE EMPLOYEE (
  CF      VARCHAR(16) PRIMARY KEY,
  AGE     INTEGER,
  SALARY  BIGINT,

);
CREATE TABLE SUBORDINATE (
  CF      VARCHAR(16) PRIMARY KEY,
  AGE     INTEGER,
  SALARY  BIGINT,
  MANAGER_CF VARCHAR(16),
  foreign key (MANAGER_CF) REFERENCES  EMPLOYEE(CF)
);
